name: Snake Game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git Snake
        run: |
          git clone https://github.com/renanCrvlh0/renanCrvlh0.git
          cd renanCrvlh0
          
          python snake_game.py
